### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by devnes** [Skycoder42/QtAutoUpdater#1]
QtAutoUpdater/qtautoupdater.pri: No such file or directory

**Comment by Skycoder42** [comment]
You will have to dowload one of the release packages. The pri is included there. But I can see I forgot to add it to the repository.

Please note that you have to build the libraries for the pri to work.

**Comment by Skycoder42** [comment]
I added the pri to the project. After you built it, adjust the paths in there or take the references you need. Hope this fixes the problem for you.
