### ISSUE TITLE
QtAutoUpdater

### ISSUE THREAD

**Issue by SmathiLagui** [Skycoder42/QtAutoUpdater#10]
Hello,

Your module QtAutoUpdater is so amazing but I have some trouble with it.
I'm working on an app with your module, on your Wiki page for the **"**UpdateController**"** section it's said : "_This example is reduced! for a full example with all parts of the controller, check the Tests/WidgetsTest application._" but the **"**WidgetsTest**"** folder doesn't exist.
I also try to use this module in another C++ class (QMainWindow or QWidget), but it doesn't work. How to use your module with another QMainWindow or QWidget ?

Cordially,
Alex

**Comment by Skycoder42** [comment]
Sorry about that one, seems I didn't update the path in the documentation. It is located in: https://github.com/Skycoder42/QtAutoUpdater/tree/master/examples/autoupdatergui/WidgetsUpdater.

Have a look at that example maybe you can see what you missing. If not, please post some code (or the link to your repository), so I can have a look at it. Not shure what you mean by "in another class".

**Comment by SmathiLagui** [comment]
Thank you for the answer. For "in another class" I wanted to put a an update button in a QWidget, not in the main.cpp, but now with your example, everything is good now.
Thank you !
Alex
