### ISSUE TITLE
dialogmaster.h: No such file or directory

### ISSUE THREAD

**Issue by bernhardHartleb** [Skycoder42/QtAutoUpdater#12]
Trying to follow the instructions in the README, the library does currently not build:

> progressdialog.cpp:5:10: fatal error: dialogmaster.h: No such file or directory
>  #include <dialogmaster.h>
>           ^~~~~~~~~~~~~~~~
> compilation terminated.

To replicate:
git clone https://github.com/Skycoder42/QtAutoUpdater.git
cd QtAutoUpdater
qmake
make qmake_all
make

I am using Qt 5.9.2 and the Qt IFW 3.0. According to the documentation, no additional tools or dependencies should be required for the build.

Please let us know what is missing. Thanks!

**Comment by Skycoder42** [comment]
My bad, you do indeed need another tool, [qpm](https://github.com/Cutehacks/qpm). Install it and run `qpm install` in the 3rdparty folder. The full commands would be:

```
cd QtAutoUpdater
cd src/3rdparty && qpm install && cd ../..
qmake
make qmake_all
make
```

This should fix the problem. I will update the README accordingly
