### ISSUE TITLE
Show negative update result on start

### ISSUE THREAD

**Issue by SmathiLagui** [Skycoder42/QtAutoUpdater#13]
Is there a way to check for updates at the launch of the application and notify user? If there no update, there is no notification.

**Comment by Skycoder42** [comment]
Have a look at [`QtAutoUpdater::Updater::DisplayLevel`](https://skycoder42.github.io/QtAutoUpdater/class_qt_auto_updater_1_1_update_controller.html#a3c3df76116942329e05f639e60bbf5a2). All you need to do is to pass the level you want to the start method.

If want for for example all info dialogs (even no updates), but no progress, use `start(QtAutoUpdater::Updater::ExtendedInfoLevel)` Check the [Example](https://github.com/Skycoder42/QtAutoUpdater/tree/master/examples/autoupdatergui/WidgetsUpdater) to see what you can do, or read the documentation.
