### ISSUE TITLE
I can't find Qt Auto Updater modules from "Select Components" page (Duplicates #6)

### ISSUE THREAD

**Issue by stephenxin** [Skycoder42/QtAutoUpdater#23]
Sorry,but I can't find Qt Auto Updater modules from "Select Components" page.
I do as this page told,https://github.com/Skycoder42/QtModules/blob/master/README.md#add-my-repositories-to-qt-maintenancetool.
but only qt modules appeared,is it avaliable with qt5.12.3 on windows.
Can you help,thanks.

**Comment by Skycoder42** [comment]
Is the Qt Modules empty? (I.e. can you see the little triangle next to the checkbox?) If yes, try expading it, maybe you just don't see the entry yet.

It could also be just a visual bug. Try selecting the modules and continue with the installation. Maybe the Module will be automatically installed without you having to see it.

Please post a screenshot of what you just described, so I can see whats not working.

**Comment by stephenxin** [comment]
Sorry for delayed reply.
![Image](https://user-images.githubusercontent.com/22423650/57445245-825ea100-7284-11e9-9224-465bda2553cd.png)
![Image](https://user-images.githubusercontent.com/22423650/57445262-8a1e4580-7284-11e9-8483-d25deb198dee.png)
![Image](https://user-images.githubusercontent.com/22423650/57445282-8ee2f980-7284-11e9-8126-334b470451d4.png)

**Comment by Skycoder42** [comment]
Ah you are using the offline installer! This is not supported, because the offline installer does not know about many components and thus fails to resolve (as you can see in the error message) See https://github.com/Skycoder42/QtAutoUpdater/issues/6#issuecomment-315551672.

However, due to recent changes in my archtiecture it might still be possible.

Please try to add the following URL under "user defined repositories" **instead** of the default URL (and remove the old one from user defined and temporary repositories)

```
https://install.skycoder42.de/qtmodules/windows_x86/qt5123/
```

This is a direct link to Qt 5.12.3 instead of the meta repository that contains all Qt versions.

**Comment by stephenxin** [comment]
Hi，thanks for help,I tried, but it seems nothing has changed. What am I missing?And sorry, I don't know what does “Remove my custom repositories”mean in another issue you show.
![test](https://user-images.githubusercontent.com/22423650/57463550-92d74180-72ad-11e9-94ed-1ed4b7ea90b3.png)

**Comment by Skycoder42** [comment]
Okay, so it seems it is still impossible to get this to work with the offline installer... I am afraid you have to either switch to the online installer or directly download the binaries from the releases. Your call.

I am aware that this is very inconvenient, but I can't do anything about this, it's a shortcoming of the Qt maintenancetool itself... I will close the issue as unfixable, but if you have further questions, feel free to ask.

**Comment by stephenxin** [comment]
I reinstalled Qt with your repository,and now it works,thanks so mush.And I wonder if we can customize MaintenanceTool so that main program can restart after update finished.

**Comment by Skycoder42** [comment]
Perfect. Regarding the restarting, see the `<RunProgram>` element of the configuration file: https://doc.qt.io/qtinstallerframework/ifw-globalconfig.html

**Comment by stephenxin** [comment]
Got it,thank you!
