### ISSUE TITLE
qtautoupdater not included when building qt statically on Mac

### ISSUE THREAD

**Issue by IQ-raf** [Skycoder42/QtAutoUpdater#24]
I am using qtautupdater in one of my apps, I need to build the app (and Qt) statically for release. It works perfectly fine on windows, but when I try to build qt statically on my Mac it never includes the qtautoupdater library. I can build my app fine when I use the non-static version of qt (where I originally added QtAutoUpdater).

Is there some extra steps I need to take to include this library when I build qt statically ?

**Comment by Skycoder42** [comment]
Please check the following steps to find out where the library gets lost

1. When building statically, the library file should be generated. Can you find this file in the build folder of QtAutoUpdater
2. Do you install the static Qt? If yes, check if the library was copied to the install location
3. Finally, when building your app, is the library added to the linker line in the makefile

**Comment by IQ-raf** [comment]
I do have the library files where qtautoupdater is built, here are the files in this lib folder: 
cmake				
libQt5AutoUpdaterCore_debug.la
libQt5AutoUpdaterCore.la	
libQt5AutoUpdaterCore_debug.prl
libQt5AutoUpdaterCore.prl	
pkgconfig

But I don't see those libraries in the place where I installed the static version of Qt

should I just manually drag and drop them there ?

**Comment by Skycoder42** [comment]
Did you run `make install` after compiling the library? If not, do so. If yes, please copy the file `src/autoupdatercore/Makefile` (and if existant `src/autoupdatercore/Makefile.Release`) from the build folder and upload them here, so I can check, why those were not installed.

(And yes, as a workaround, you can indeed just copy them, but that won't solve the undelying issue...)

**Comment by dskart** [comment]
So I configure Qt with `src/configure -static -release -prefix "pathtofolder/static"`
Then I run `make` and `make install`
every other library is built and installed correctly in the "pathtofolder/static" but not the qtautoupdater library. It doesn't even seem to be built (no lib folder is created in src/qtautoupdater).

I then run `qmake` `make` and `make install` inside of `src/autoupdater`. The library seems to be built after I run `make` but I get an error with `make install`.

here is the makefile that is created from running  `qmake` in `src/autoupdater`.
[Makefile.txt](https://github.com/Skycoder42/QtAutoUpdater/files/3214220/Makefile.txt)

**Comment by IQ-raf** [comment]
The comment above was me, sorry I forgot to change users on github.

**Comment by Skycoder42** [comment]
The reason why QtAutoUpdater is not build automatically from toplevel is that Qt does not know about the module. You would have to edit the `.gitmodules` files before running configure to include it. Running manually however normally works.

Now, the Makefile you gave me is the wrong one. You gave me the one in the `Src/qtautoupdater` folder, I need the one in `Src/qtautoupdater/src/autoupdater`. Sorry for not beeing clear enough about that.

Finally, if you get an error on `make install`, that would probably be even more usefull. Please copy the output into a file (or run `make install &> make_install.log`) and upload that one here as well.

**Comment by IQ-raf** [comment]
That is super weird that At does not know about the module, I downloaded it from Qt's maintenance tool and did not have any issue on windows.

here is the make file from `Src/qtautoupdater/src` (that was the only path that had a makefile) and I also have the log of when I run `make install` from `Src/qtautoupdater`
[Makefile.txt](https://github.com/Skycoder42/QtAutoUpdater/files/3217690/Makefile.txt)
[make_install.log](https://github.com/Skycoder42/QtAutoUpdater/files/3217691/make_install.log)

**Comment by Skycoder42** [comment]
Analysing the log, we get the following error:
```
Error copying ../../lib/libQt5AutoUpdaterCore.a to /usr/local/Qt-5.12.1/lib/libQt5AutoUpdaterCore.a: Cannot create /usr/local/Qt-5.12.1/lib/libQt5AutoUpdaterCore.a for output
```
So apparently you have no permission to install the library in `/usr/local` - try `sudo make install` instead.

**Comment by IQ-raf** [comment]
Oh wow, that is a stupid error from my part and that makes a lot of sense. So now it got built and installed in `usr/loca/Qt-5.12.1/lib`. Is there any way I can install it in a different location such as `PathToStaticQt/Static`.  Basically, do the same thing as the `-prefix` argument when I configure Qt to be built statically.

**Comment by Skycoder42** [comment]
Normally, qmake should pick up the prefix automatically. I.e. if you compile with Qt with `-prefix PathToStaticQt/Static`, the the library should be installed to the very same location. Make shure you use the correct qmake (e.g. `PathToStaticQt/Static/bin/qmake`, but then that should be the case.

Note: I looked at the makefile you uploaded, and it says `QMAKE = /usr/local/Qt-5.12.1/bin/qmake` - which is why it was installed to that location. You can check this yourself after running qmake to see if the correct one was chosen.

The full command to first build and install Qt and then the library thus should be something like:
```
# Qt
src/configure -static -release -prefix "PathToStaticQt/Static"
make
[sudo] make install

# QtAutoUpdater
PathToStaticQt/Static/bin/qmake
make
[sudo] make install
```

**Comment by IQ-raf** [comment]
This is amazing, it finally worked. Thanks a lot for your patience and help. This library is amazing and saved me a ridiculous amount of time and work!

**Comment by Skycoder42** [comment]
Perfekt! Always happy to help
