### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by abdullah-radwan** [Skycoder42/QtAutoUpdater#28]
Hello,
I've translated the library to Arabic to use with my project. [Here is the translation file](https://github.com/Skycoder42/QtAutoUpdater/files/3403545/translations.zip).

**Comment by abdullah-radwan** [comment]
Here is an updated translation: [qtautoupdatergui_ar.zip](https://github.com/Skycoder42/QtAutoUpdater/files/3586388/qtautoupdatergui_ar.zip)

**Comment by Skycoder42** [comment]
I am currently working on Version 3.0 of the library. I will add the translations, but it would be nice if you could update them once again as soon as 3.0 gets released. Thanks for your contribution.

Note: It's always faster and easier for me, if you do such contributions via a pull-request.

**Comment by Skycoder42** [comment]
The translations have been updated on the [major branch](https://github.com/Skycoder42/QtAutoUpdater/tree/major/src/translations). It was auto-translated using https://www.matecat.com/. It would be awesome if you could verify the correctness of the generated translations. Thanks.

**Comment by abdullah-radwan** [comment]
Sorry for the delay. Here is the updated translation:  [qtautoupdater_ar.zip](https://github.com/Skycoder42/QtAutoUpdater/files/3694285/qtautoupdater_ar.zip)

I can say the auto translator is 50-60% good.
