### ISSUE TITLE
QtAutoUpdater::Updater::create returns NULL on the release configuration

### ISSUE THREAD

**Issue by abdullah-radwan** [Skycoder42/QtAutoUpdater#31]
I've noticed that QtAutoUpdater::Updater::create method works on the debug configuration, but returns NULL on the release configuration. No errors in the log (I've installed a message handler, so any messages by AutoUpdater should be written in the log).

Code:
```
MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent), ui(new Ui::MainWindow)
{
    // Code above

    updater = QtAutoUpdater::Updater::create("qtifw", {{"path", qApp->applicationDirPath() + "/maintenancetool"}}, qApp);

    connect(updater, &QtAutoUpdater::Updater::checkUpdatesDone, [&](QtAutoUpdater::Updater::State state)
    {
        switch (state)
        {
        case QtAutoUpdater::Updater::State::Error:
            qDebug() << "An error occured.";
            config.checkUpdates = false;
            break;
        case QtAutoUpdater::Updater::State::NoUpdates:
            qDebug() << "No updates are found";
            break;
        case QtAutoUpdater::Updater::State::NewUpdates:
            qDebug() << "An update is found" << updater->updateInfo();
            break;
        default: break;
        }
    });
}
```
Log file: `QObject::connect(QtAutoUpdater::Updater, Unknown): invalid null parameter`. This error is because `updater` is NULL. No other errors releated to AutoUpdater exists in the log.

No errors in the log file with the debug configuration. Everything works as expected.

I am using Qt 5.13.1 on Windows, and QtAutoUpdater 3.0 downloaded from the Qt maintenance tool repository.

**Comment by Skycoder42** [comment]
Verify interesting. That should not happen, as I test both debug and release configration with the CI system. I will try to reproduce your problem tomorrow.

Until then, could you check the contents of the `<Qt-Install-Dir>\5.13.1\<platform>\plugins\updaters` directory and see if it contains both, the `qtifw.dll` and the `qtifwd.dll`?

**Comment by abdullah-radwan** [comment]
That's it! I use `windeployqt` tool to get DLLs for Windows, and it doesn't include `qtifw.dll`. After adding to the release version DLLs, it worked.

So this is the file structure:
```
--- app.exe
--- updaters/qtifw.dll
--- Qt DLLs...
```

**Comment by Skycoder42** [comment]
Perfekt. That is true. windeployqt sadly does not pick up additional plugins...
