### ISSUE TITLE
How should I check for updates with a temporary repository?

### ISSUE THREAD

**Issue by fengcanyue** [Skycoder42/QtAutoUpdater#32]
I want to use this feature in my code:"maintenancetool.exe --addTempRepository http://192.168.1.143:8080/repository". But I don't know how to use you  library to do this.I found something like this " { {"extraCheckArgs", "someArg=tree"} } ",maybe it'll work.Could you give some advice?Thank you very much.

**Comment by Skycoder42** [comment]
That's exactly what you need to do. I would show you the documentation, but apparently I forgot to upload it to github pages... I will do so soon.

Use the `extraCheckArgs` as extra configuration value, e.g. In the constructor, where you specify the `path` as well.

If you use the feature to start the installation as well, use the same value for `extraInstallArgs`

**Comment by fengcanyue** [comment]
就没了你9你几句话哦平均o9hnk线佛人那好呀@Skycoder42

**Comment by fengcanyue** [comment]
` auto updater = QtAutoUpdater::Updater::create(QStringLiteral("qtifw"), {
            {"path", "E:\\Qt\\Qt5.13.1\\MaintenanceTool.exe"}, {"extraCheckArgs", "--addTempRepository=http://192.168.1.143:8080/repository/Msetp-teacher"}
        }, qApp);`
I use this code,but get the error message ,`Cannot retrieve remote tree No package sources set for this application..`,

**Comment by Skycoder42** [comment]
This looks like a problem with the Qt installer framework, not the library. Please try to manually invoke the maintenance tool as:
```
E:\Qt\Qt5.13.1\MaintenanceTool.exe --checkupdates --addTempRepository=http://192.168.1.143:8080/repository/Msetp-teacher
```
And check the output. If you get the same error, than it's not a problem of the library, but QtIFW. If it works like that, try to enable debug logging, it might help to find out more. You can do so by setting the following environment variable:
```
QT_LOGGING_RULES=qt.autoupdater.*.debug=true
```
**EDIT:** Are you using the offline installer? If yes, that might be the reason for why it does not work...

**Comment by fengcanyue** [comment]
Yes.I am using the offline installer.My online repository IP changes all the time, but my Qt application know it. So,I want to use temp repository to check updates.Now ,I down konw how to do.Could you give some advice?

**Comment by Skycoder42** [comment]
As far as I know, it is not possible to do updates via the offline installer. It is offline, after all. Have you tried to run it by hand?

**Comment by fengcanyue** [comment]
I've tried to run it by hand.It displays the same error message:`[0] Operations sanity check succeeded.
[1] Cannot retrieve remote tree No package sources set for this application..`.But I can check updates via the offline installer with gui interface. also use the temp repository.It  let me very confused.

**Comment by Skycoder42** [comment]
Well, there is nothing I can do in this case. I do not know why it works via the GUI but not via the `--checkupdates`. That mode is required for the plugin, as otherwise there is no usable output to get update information from. 

You should create an issue regarding that problem at [bugreports.qt.io](https://bugreports.qt.io/secure/Dashboard.jspa). If you do so, please post a link here.

I will close this issue now, as it is nothing I can fix, but if you have further questions, ideas, etc. feel free to comment on or reopen it.
