### ISSUE TITLE
Error while installing module with Qt 5.8.0-1

### ISSUE THREAD

**Issue by julian-poidevin** [Skycoder42/QtAutoUpdater#6]
When trying to install **QtAutoUpdater** module with **MaintenanceTool**, the following message appers :

![capture](https://cloud.githubusercontent.com/assets/8756421/25848819/52a40e80-34bc-11e7-8cda-7bce22439cb0.PNG)
 
Should I try running on an other compiler or version of Qt ?

Thanks.

**Comment by Skycoder42** [comment]
Please answer the following questions to narrow down the problem:
1. Does this happen before you can select the kits to install? (i.e. when downloading meta information). Or does it happen after you already selected autoupdater in the tree
2. Did you install the "Qt Online Installers", or the offline version (for only one kit, "Windows Host" in the download section here: https://www.qt.io/download-open-source/#section-2)?

In case you are using the offline version, that's the problem. The repository is concipated for the online installer. Using the online installer will solve the problem. If thats not an option for you, or you are not using the offline version, please tell me so I can find a solution.

**Comment by Skycoder42** [comment]
In case you are really using the offline installer, I do have an idea how to fix it without reinstalling Qt. I can try it if thats the case.

**Comment by julian-poidevin** [comment]
Thank you for considering my problem.

1. It's happening while fetching meta info.
2. I installed Qt Offline with :  [qt-opensource-windows-x86-msvc2015-5.8.0.exe](https://download.qt.io/archive/qt/5.8/5.8.0/qt-opensource-windows-x86-msvc2015-5.8.0.exe)

I can reinstall using online tool but it would be great if your tool could work also for offline installation.

**Comment by Skycoder42** [comment]
Okay, I will try if this can be fixed by adjusting the dependencies. I won't have a windows machine until friday, so I can't test it until then. I will notify you once I'm finished

**Comment by julian-poidevin** [comment]
If you want me to try, just give me the instructions, I'll be glad to help.

**Comment by Skycoder42** [comment]
Okay, I modified the autoupdater xml accordingly. Please do the following steps to test my change:
1. Remove my custom repositories, the one you added and the ones that have been added automatically. Disable the following repositories (by unchecking them in the network settings):
    - QtDataSync Windows Repository
    - QtRestClient Windows Repository
    - QtBackgroundProcess Windows Repository
    - QtJsonSerializer Windows Repository
    - https://install.skycoder42.de/qtmodules/windows_x86/ (the custom one)
2. Make shure the "QtAutoUpdater Windows Repository" exists and is checked. This way you will only download the dependencies for autoupdater, because those are the only ones I changed for testing.
3. Try to install again, and report the result :D If my guess is correct, this should solve the issue.

**Comment by julian-poidevin** [comment]
Ok, just tried following your instructions. I can now get a bit further, getting meta info and had this window prompted : 
![capture2](https://cloud.githubusercontent.com/assets/8756421/25936844/a12fac4e-3629-11e7-8d14-798b7dd6c8e0.PNG)

Selected your module and clicked "Yes". At this point, update of the components fails while downloading archive for `Qt Auto Update Documentation`. I got this message : 
![capture3](https://cloud.githubusercontent.com/assets/8756421/25936890/da53fef8-3629-11e7-8819-6c0502fb083d.PNG)

Thanks for your help.

**Comment by Skycoder42** [comment]
Okay... At least the repository works now :joy: Apparently, I have to adjust the script as well... Please check your Qt installation directory, does the folder `Docs/Qt-5.8/` exist?

**Comment by julian-poidevin** [comment]
Yes, good work :wink:. The directory exists : 
![docs](https://cloud.githubusercontent.com/assets/8756421/25945473/53f9408e-3647-11e7-8e5a-fe8bf7209b13.PNG)

**Comment by Skycoder42** [comment]
So, apparently this function is not defined on the maintenancetool of an offline installation. I fixed this by make the call optional. However, this means you won't see the documentation in QtCreator, unless you add it by hand (See [Qt - Adding External Documentation](https://doc.qt.io/qtcreator/creator-help.html#adding-external-documentation)). On my test machine, the rest of the installation worked fine. Please verify it and close the issue.

However, I still recommend to use the online installer - if possible - it's faster and works more reliable...

**Comment by julian-poidevin** [comment]
Yup, works fine now ! Thanks a lot.

**Comment by Skycoder42** [comment]
Repopening this. Apparently, it does influence the online installer: If not present, the Auto-Dependencies are installed automatically, thus forcing you to install all compilers I provide the module for. Thus I reverted this. The offline installer will fail again, but you can still simply download the bundle from the release pages, if the online installer is no option.

I'll do further investigation in hope to find a solution for both sides.

**Comment by Skycoder42** [comment]
A solution seems to be impossible for now. Closing in favor of the online installer.
